### ISSUE TITLE
Interpreting training graphs

### ISSUE THREAD

**Issue by ipsec** [HorizonRobotics/alf#1139]
Hi all,

First congratulations by excellent project.

I'm training a custom environment using muzero config (muzero_pendulum_conf.py).
```
python -m alf.bin.train --conf alf/examples/muzero_pendulum_conf.py \
--root_dir ~/tmp/custom/ \
--conf_param create_environment.env_name="'gym_games:Custom-v0'" \
--conf_param SimpleMCTSModel.num_sampled_actions=20 \
--conf_param TrainerConfig.num_iterations=100000
```

I'm getting this graph.

![Captura de Tela 2021-12-10 às 09 09 42](https://user-images.githubusercontent.com/79345/145600906-8d21d100-b107-4b69-9999-1a9bdb649afc.png)

How can I interpretate this graph?
What's happening near 10k? Overfitting?
All other graphs have same behavior.

**Comment by Haichao-Zhang** [comment]
This is only related to logging and not training.  It is because of the tensorboard logging rate change at 10k point (``summary_interval``).

In ALF, at the beginning of training (before reaching ``summary_interval``) the tensorboard logging is done for each step for debugging purpose, and then switch to ``every summary_interval`` steps after that:
https://alf.readthedocs.io/en/latest/tutorial/summary_metrics_and_tensorboard.html?highlight=global%20step%20is%20less%20than%20%60%60summary_interval%60%60#turning-on-off-summary


As your ``num_iterations=100000``, and the ``num_summaries=100``  (set in ``alf/examples/muzero_pendulum_conf.py``), 
this gives an effective ``summary_interval=num_iterations/num_summaries=1000`` training iterations.
This translates to ``10K`` env steps as ``unroll_length=10`` (set in ``alf/examples/muzero_pendulum_conf.py``).

**Comment by ipsec** [comment]
Hi @Haichao-Zhang ,

Thanks for the quick response.

**Comment by hnyu** [comment]
> Hi @Haichao-Zhang ,
> 
> Thanks for the quick response.

Just a quick note on the summary interval. If you don't want to manually calculate the interval length, you can instead specify the config `TrainerConfig.num_summaries` to have a fixed number of summary points no matter how long you will train the job. 

Also to turn off summarizing at every iteration before `summary_interval`, you can set `TrainerConfig.summarize_first_interval=False`.
