### ISSUE TITLE
About Allocating Custom Environment

### ISSUE THREAD

**Issue by reinforcementwonder** [HorizonRobotics/alf#1297]
Thanks for the great project. 

I am now dealing with a custom environment, where each instance would take up one GPU for simulation. The instantiation of the environment looks like: `gym.make(`env_name`, gpu_index=x)`. In this case, I wonder how should I modify the `create_environment` configuration to support this?

```
alf.config(
    "create_environment", env_name="Pendulum-v1", num_parallel_environments=4) #assuming there are 4 GPUs available and we will instantiate 4 environments, one for each GPU.
```

Thanks in advance for any suggestions or advices.

**Comment by hnyu** [comment]
> Thanks for the great project.
> 
> I am now dealing with a custom environment, where each instance would take up one GPU for simulation. The instantiation of the environment looks like: `gym.make(`env_name`, gpu_index=x)`. In this case, I wonder how should I modify the `create_environment` configuration to support this?
> 
> ```
> alf.config(
>     "create_environment", env_name="Pendulum-v1", num_parallel_environments=4) #assuming there are 4 GPUs available and we will instantiate 4 environments, one for each GPU.
> ```
> 
> Thanks in advance for any suggestions or advices.

Hi @reinforcementwonder , the code for `create_environment` is at 

https://github.com/HorizonRobotics/alf/blob/pytorch/alf/environments/utils.py#L60

Its args include:

``` python
@alf.configurable
def create_environment(env_name='CartPole-v0',
                       env_load_fn=suite_gym.load,
                       num_parallel_environments=30,
                       nonparallel=False,
                       seed=None,
                       batched_wrappers=()):
``` 

By default, the env load function would be `suite_gym.load` and it will be called at

https://github.com/HorizonRobotics/alf/blob/pytorch/alf/environments/utils.py#L120

So one way for your case would be to add a gpu index arg for `suite_gym.load` and pass the id to it by something like:

``` python
alf_env = parallel_environment.ParallelAlfEnvironment(
            [functools.partial(env_load_fn, env_name, gpu=i) for i in range(num_parallel_environments)],
            flatten=True)
```

And inside `suite_gym.load`, 

https://github.com/HorizonRobotics/alf/blob/pytorch/alf/environments/suite_gym.py

do 

``` python
gym_spec = gym.spec(environment_name)
gym_env = gym_spec.make(gpu_index=gpu)
```

If you use your own defined suite instead of `suite_gym`, then you can do the same thing and configure 

``` python
alf.config("create_environment", env_load_fn=suite_yours.load, ....)
```

Let me know if you have further questions.

**Comment by hnyu** [comment]
Turns out there is a much simpler way by just using the `env_id` arg of `suite_gym.load`. So still in 

https://github.com/HorizonRobotics/alf/blob/pytorch/alf/environments/suite_gym.py

do 

``` python
gym_spec = gym.spec(environment_name)
gym_env = gym_spec.make(gpu_index=env_id)
```
`env_id` will be 0, 1, 2, ...

**Comment by reinforcementwonder** [comment]
Hi @hnyu. Thanks for explaining all these mechanisms. It worked!
