### ISSUE TITLE
Make sure environments in SocialRobot work with tf_agents

### ISSUE THREAD

**Issue by emailweixu** [HorizonRobotics/alf#3]
We want to be able to run SocialRobot environment with tf_agents. There are two issues:
1. Since tf_agents run step() of an environment in a thread different from the thread it is created, somehow SocialRobot will crash when it's used this way

2. We want to run multiple SocialRobot environments. And each environment needs to be in a separate process because of Gazebo.  Hence we need have an environment wrapper to wrap an environment in a separate process while use it like in the same process. This is similar to https://github.com/deepmind/scalable_agent/blob/master/py_process.py, which is used here https://github.com/deepmind/scalable_agent/blob/6c0c8a701990fab9053fb338ede9c915c18fa2b1/experiment.py#L437

**Comment by witwolf** [comment]
1. SocialRobot should run in the same thread that it is created because of its inner implementation (gazebo::sensors) . There are three options to solve this to work with tf_agents: 1) move the creation from main thread to `BatchedPyEnvironment`  2) using `ParallelPyEnvironment`  3) wrap gazebo interface in one thread . Since gazebo can not spawn multi instances by multi-threads 1) and 3) is not necessery


2. tf_agents support parallel environments using multi-threads (`BatchedPyEnvironment`) or mutil-process (`ParallelPyEnvironment`)



example to work with tf_agents
[train_eval.txt](https://github.com/HorizonRobotics/alf/files/3042603/train_eval_ddpg.txt)

diff with [tf_agents/agents/ddpg/examples/v2/train_eval.py](https://github.com/tensorflow/agents/blob/master/tf_agents/agents/ddpg/examples/v2/train_eval.py)
[train_eval.patch.txt](https://github.com/HorizonRobotics/alf/files/3042611/train_eval.patch.txt)

**Comment by emailweixu** [comment]
👍 
Is it possible to make some wrap for socialrobot environment so that we don't need to change tf_agents code to run with social robot environment. It will be cool if that's possible.

**Comment by witwolf** [comment]
> Is it possible to make some wrap for socialrobot environment so that we don't need to change tf_agents code to run with social robot environment？ It will be cool if that's possible.

All examples in tf_agents (`tf_agents/agents/*/examples/v*/*`) creates at least two environments `tf_env` (created in self process by `BatchedPyEnvironment` or created in new process by `ParallelPyEnvironment ` for collect data)  and `eval_tf_env` (1 instance created in self process for test ) . Since many singletons implementation in gazebo multi instances in one process  is not supported, partial examples that created `tf_env` and `eval_tf_env` in the same process can not run without changing code .  Besides, different port should be  specified explicitly or generate randomly .

**Comment by emailweixu** [comment]
A possible implementation would be to wrap socialbot using ProcessPyEnvironment in socialbot_suite. For port, we can automatically do increment from a given starting port (from environment).  So it can be used in the same way as other environment.

**Comment by witwolf** [comment]
> A possible implementation would be to wrap socialbot using ProcessPyEnvironment in socialbot_suite. For port, we can automatically do increment from a given starting port (from environment). So it can be used in the same way as other environment.

with commit update [wrap with process](https://github.com/HorizonRobotics/alf/pull/5/commits/636f59053cf7b9b7c1db25b3f91345291a10930d) and config.gin :
> import alf.environments.suite_socialbot
>
> train_eval.env_name = "SocialBot-Pr2Gripper-v0"
> train_eval.env_load_fn = @suite_socialbot.load
> train_eval.num_parallel_environments = 2
>
> suite_socialbot.load.wrap_with_process = False  # recommend set to False when num_parallel_environments > 2 

we can run trainning as 

`python -m tf_agents.agents.ddpg.examples.v2.train_eval --gin_file=config.gin  --root_dir=~/tmp/ddpg/socialbot/Pr2Gripper`
