### ISSUE TITLE
different version gin-config

### ISSUE THREAD

**Issue by ChenyangRan** [HorizonRobotics/alf#648]
HI, I have installed  the alf and socialrobot many time.
However, the error 'no module name gin.torch' raised each time.
I have installed the latest gin-config from google, but the error is the pkg needs the 0.4.0.
Could you help me?
By the way, if I just want to use the socialrobot and test the code, which version of alf should I install?

**Comment by jesbu1** [comment]
Hi, please install the gin listed in alf’s setup.py file.

The social robot gin requirement is outdated.

**Comment by jesbu1** [comment]
If you want to just use socialrobot and test the code, the current version of alf on the pytorch branch should work without issues, other than that gin-config discrepancy.

**Comment by hnyu** [comment]
> HI, I have installed the alf and socialrobot many time.
> However, the error 'no module name gin.torch' raised each time.
> I have installed the latest gin-config from google, but the error is the pkg needs the 0.4.0.
> Could you help me?
> By the way, if I just want to use the socialrobot and test the code, which version of alf should I install?

First uninstall whatever gin version in your system. And then please run "pip install -e ." in ALF's root and this will install our forked gin. 

If you want to test ALF on socialrobot envs, then install ALF after socialrobot because the requirements of ALF should overwrite those of socialrobot.  ALF can just be the default pytorch version.
